### ISSUE TITLE
hostsfile cookbook fails on SMARTOS

### ISSUE THREAD

**Issue by joshzitting** [customink-webops/hostsfile#68]
This cookbook fails when trying to insert an IP address with an invalid IP address error... 

Here is the code that calls it.. 

```ruby
hostsfile_entry db_host[0][:ipaddress] do
  hostname db_host[0][:hostname]
  aliases ['dbhost']
  unique true
end
```

Here is the data that is used... 

```tetxt
         * log[[{"name":"test-server","chef_environment":"integration","json_class":"Chef::Node","automatic":{"ipaddress":"10.129.10.200","hostname":"test-server-precise64","fqdn":"test-server-precise64.vagrantup.com","keys":{"ssh":{"host_rsa_public":"random_pub_key"}},"port":"5043"},"normal":{},"chef_type":"node","default":{},"override":{},"run_list":["role[p3-gw]"]}]] action write
```

Here is the error... 

```text
         * hostsfile_entry[10.129.10.200] action create

           ================================================================================
           Error executing action `create` on resource 'hostsfile_entry[10.129.10.200]'
           ================================================================================

           IPAddr::InvalidAddressError
           ---------------------------
           invalid address

           Cookbook Trace:
           ---------------
           /tmp/kitchen/cache/cookbooks/hostsfile/libraries/entry.rb:117:in `new'
           /tmp/kitchen/cache/cookbooks/hostsfile/libraries/entry.rb:117:in `initialize'
           /tmp/kitchen/cache/cookbooks/hostsfile/libraries/entry.rb:54:in `new'
           /tmp/kitchen/cache/cookbooks/hostsfile/libraries/entry.rb:54:in `parse'
           /tmp/kitchen/cache/cookbooks/hostsfile/libraries/manipulator.rb:250:in `block in collect_and_flatten'
       /tmp/kitchen/cache/cookbooks/hostsfile/libraries/manipulator.rb:249:in `each'
       /tmp/kitchen/cache/cookbooks/hostsfile/libraries/manipulator.rb:249:in `collect_and_flatten'
       /tmp/kitchen/cache/cookbooks/hostsfile/libraries/manipulator.rb:45:in `initialize'
       /tmp/kitchen/cache/cookbooks/hostsfile/providers/entry.rb:137:in `new'
           /tmp/kitchen/cache/cookbooks/hostsfile/providers/entry.rb:137:in `hostsfile'
           /tmp/kitchen/cache/cookbooks/hostsfile/providers/entry.rb:30:in `block in class_from_file'

           Resource Declaration:
           ---------------------
           # In /tmp/kitchen/cache/cookbooks/p3_config/recipes/default.rb

           156:     hostsfile_entry db_host[0][:ipaddress] do
       157:       hostname db_host[0][:hostname]
           158:       aliases ['dbhost']
           159:       unique true
       160:     end
           161:   end

           Compiled Resource:
           ------------------
           # Declared in /tmp/kitchen/cache/cookbooks/p3_config/recipes/default.rb:156:in `from_file'

           hostsfile_entry("10.129.10.200") do
             action :create
             retries 0
             retry_delay 2
             default_guard_interpreter :default
         declared_type :hostsfile_entry
             cookbook_name "p3_config"
         recipe_name "default"
         hostname "test-server-precise64"
             aliases ["dbhost"]
             unique true
           end


       Running handlers:
```

We use the same recipe, test node data, and ip address on ubuntu and it works just fine. We think it is something with the IPv6 part of the libraries/entry.rb or the IPADDR ruby... 

Thanks!

**Comment by sethvargo** [comment]
What version of Ruby and Chef?

**Comment by joshzitting** [comment]
ruby --version
ruby 2.0.0p598 (2014-11-13 revision 48408) [x86_64-solaris2.11]
Chef: 12.1.2

**Comment by sethvargo** [comment]
@joshzitting can you please post your current hostsfile? I can't repro.

**Comment by joshzitting** [comment]
```
[root@default-smartos ~]# cat /etc/hosts
::1             localhost
127.0.0.1       localhost loghost
10.129.21.248   default-smartos
        b3db6142-2b4a-c974-8d35-81f224b965ff    loghost
```

**Comment by joshzitting** [comment]
as soon as I took that extra line out it converged.. 
Let me do a little more testing and see if I can pinpoint where that line is coming from.

**Comment by sethvargo** [comment]
Well that line is definitely an invalid IP address, so I think the error is correct. That's not even an IPv6 address.

**Comment by joshzitting** [comment]
It looks like it is an UUID for Joyent/SDC. The Image we are using is "base 64 lts 14.4.0" or joyent_image_id: c02a2044-c1bd-11e4-bd8c-dfc1db8b0182. So that line probably needs to stay in the hosts file...

**Comment by sethvargo** [comment]
I don't understand why that would need to be in the hostfile? It's not looking anything up by that UUID, that's not how /etc/hosts works.

**Comment by sethvargo** [comment]
Even the man page says that's not valid: https://smartos.org/man/4/hosts

```text
File Formats                                             HOSTS(4)


     from each line containing a matching official name or  nick-
     name.  A call to getipnodebyname(3SOCKET) is similar, but is
     capable of returning hostent structures containing IPv4  and
     IPv6   addresses.  Applications  might  prefer  to  use  the
     address-family  independent  getaddrinfo(3SOCKET)  API   for
     name-to-address lookups.


     A `#' indicates the beginning of a comment; characters up to
     the  end  of  the  line are not interpreted by routines that
     search the file.


     Network addresses are written in one of two ways:

         o    The conventional "decimal dot" notation and  inter-
              preted  using the inet_addr routine from the Inter-
              net address manipulation library, inet(3SOCKET).

         o    The IP Version 6 protocol [IPV6],  defined  in  RFC
              1884  and interpreted using the inet_pton() routine
              from the Internet address manipulation library. See
              inet(3SOCKET).
```

**Comment by sethvargo** [comment]
Even given the paste, it appears there is a tab character before that line, leading me to believe it was manually entered.

**Comment by joshzitting** [comment]
Ok we are going to talk to joyent and see why it is in there etc. Thank you for your time and we will keep you posted! 
Thanks!

**Comment by joshzitting** [comment]
I had the format of that file wrong... the UUID and loghost are acutally aliases for localhost... See below..

```
[root@30bd320b-e4f9-6fc8-b654-e2e9aa17b843 ~]# cat /etc/hosts
::1             localhost
127.0.0.1       localhost localhost.local loghost 30bd320b-e4f9-6fc8-b654-e2e9aa17b843

[root@30bd320b-e4f9-6fc8-b654-e2e9aa17b843 ~]# ping 30bd320b-e4f9-6fc8-b654-e2e9aa17b843

30bd320b-e4f9-6fc8-b654-e2e9aa17b843 is alive

[root@30bd320b-e4f9-6fc8-b654-e2e9aa17b843 ~]#
```

So somthing in Hostsfile is not handling these aliases properly and is formatting them like this.. 

```
[root@default-smartos ~]# cat /etc/hosts
::1             localhost
127.0.0.1       localhost loghost
10.129.21.248   default-smartos
        b3db6142-2b4a-c974-8d35-81f224b965ff    loghost
```

**Comment by sethvargo** [comment]
@joshzitting something is wrong here... Are you sure you are using this cookbook? After the cookbook runs, it leaves a massive warning header at the top of the hostsfile like this

```text
#
# This file is managed by Chef, using the hostsfile cookbook.
# Editing this file by hand is highly discouraged!
#
# Comments containing an @ sign should not be modified or else
# hostsfile will be unable to guarantee relative priority in
# future Chef runs!
#
```

I do not see any of that output, and the first text box corresponds to a different machine than the second text box.

**Comment by joshzitting** [comment]
ok we found a workaround.
Thanks for your help @sethvargo! 
Josh
