### ISSUE TITLE
unknown "hostfiles" inside resource

### ISSUE THREAD

**Issue by deltamualpha** [customink-webops/hostsfile#92]
I'm getting a rather opaque error when trying to use this cookbook (3.0.1). It's called as part of a loop of host:address pairs. The cookbook depends upon `hostfiles` in the metadata.rb file.

```
node['sssd']['hosts'].each_pair do |k,v|
  hostsfile_entry k do
    hostname v
    unique   true
    action   :create
  end
end
```

    NameError
    ---------
    No resource, method, or local variable named `hostsfile' for `Custom resource hostsfile_entry from cookbook hostsfile action provider "10.30.4.38"'

    Cookbook Trace:
    ---------------
    /var/chef/cache/cookbooks/hostsfile/resources/entry.rb:35:in `block in class_from_file'
    /var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:78:in `run_action'
    /var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:106:in `block (2 levels) in converge'
    /var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:106:in `each'
    /var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:106:in `block in converge'
    /var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:105:in `converge'

**Comment by deltamualpha** [comment]
My bad, chef version was outside of supported range.
